import { Annotation } from "@langchain/langgraph";

export const PaymentState = Annotation.Root({ // PaymentState is the shared memory of the langgraph workflow
  paymentReference: Annotation({
    // Payment reference received from the API.
    default: () => "", // default value of paymentReference is empty string
  }),

  evidences: Annotation({
    // Stores investigation evidence generated by different agents
    default: () => [], // default value of evidences is empty array

    // Instead of replacing the existing evidence, appends new evidence to the existing array
    reducer: (current, update) => current.concat(update), // reducer function is used to merge the current state with the updated state
  }),

  decision: Annotation({
    // Final investigation outcome
    default: () => null, // default value of decision is null
  }),
});